services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile.web
      args:
        DOCKER_BUILDKIT: 1
    # restart: always
    env_file:
      - ./apps/web/.env
    networks:
      - dev_env
    depends_on:
      - api
    image: harbor.hwgeneralins.com/plane/web:1.2.2

  admin:
    container_name: admin
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile.admin
      args:
        DOCKER_BUILDKIT: 1
    # restart: always
    env_file:
      - ./apps/admin/.env
    networks:
      - dev_env
    depends_on:
      - api
      - web
    image: harbor.hwgeneralins.com/plane/admin:1.2.1

  space:
    container_name: space
    build:
      context: .
      dockerfile: ./apps/space/Dockerfile.space
      args:
        DOCKER_BUILDKIT: 1
    # restart: always
    env_file:
      - ./apps/space/.env
    networks:
      - dev_env
    depends_on:
      - api
      - web
    image: harbor.hwgeneralins.com/plane/space:1.2.1

  api:
    container_name: api
    build:
      context: ./apps/api
      dockerfile: Dockerfile.api
      args:
        DOCKER_BUILDKIT: 1
    # restart: always
    networks:
      - dev_env
    command: ./bin/docker-entrypoint-api.sh
    env_file:
      - ./apps/api/.env
    environment:
      - DISABLE_TELEMETRY=true
    extra_hosts:
      - 'auth.hwgeneralins.com:172.17.0.1'
    depends_on:
      - plane-db
      - plane-redis
      - plane-mq
    image: harbor.hwgeneralins.com/plane/api:1.2.2

  worker:
    container_name: bgworker
    # restart: always
    networks:
      - dev_env
    command: ./bin/docker-entrypoint-worker.sh
    env_file:
      - ./apps/api/.env
    depends_on:
      - api
      - plane-db
      - plane-redis
      - plane-mq
    image: harbor.hwgeneralins.com/plane/api:1.2.2

  beat-worker:
    container_name: beatworker
    # restart: always
    networks:
      - dev_env
    command: ./bin/docker-entrypoint-beat.sh
    env_file:
      - ./apps/api/.env
    depends_on:
      - api
      - plane-db
      - plane-redis
      - plane-mq
    image: harbor.hwgeneralins.com/plane/api:1.2.2

  migrator:
    container_name: plane-migrator
    restart: no
    networks:
      - dev_env
    command: ./bin/docker-entrypoint-migrator.sh
    env_file:
      - ./apps/api/.env
    depends_on:
      - plane-db
      - plane-redis
    image: harbor.hwgeneralins.com/plane/api:1.2.2

  live:
    container_name: plane-live
    build:
      context: .
      dockerfile: ./apps/live/Dockerfile.live
      args:
        DOCKER_BUILDKIT: 1
    # restart: always
    networks:
      - dev_env
    # command: ls -al live
    image: harbor.hwgeneralins.com/plane/live:1.2.1
    env_file:
      - ./apps/live/.env
    environment:
      - API_BASE_URL=http://api:8000

  plane-db:
    container_name: plane-db
    image: hgi-postgres:16.4
    # restart: always
    command: postgres -c 'max_connections=1000'
    volumes:
      # - ./data/postgres:/var/lib/postgresql/data
      - pgdata:/var/lib/postgresql/data
    networks:
      - dev_env
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data

  plane-redis:
    container_name: plane-redis
    image: valkey/valkey:7.2.11-alpine
    # restart: always
    networks:
      - dev_env
    volumes:
      - redisdata:/data

  plane-mq:
    container_name: plane-mq
    image: rabbitmq:3.13.6-management-alpine
    # restart: always
    networks:
      - dev_env
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  plane-minio:
    container_name: plane-minio
    image: minio/minio
    # restart: always
    command: server /export --console-address ":9090"
    volumes:
      - ./data/uploads:/export
    networks:
      - dev_env
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}

  # Comment this if you already have a reverse proxy running
  proxy:
  # 인증서버 로컬 사용위해 컨테이너 명 지정
    container_name: plane.hgi.com
    build:
      context: ./apps/nginx
      dockerfile: Dockerfile
    # restart: always
    ports:
      - ${NGINX_PORT}:18080
    networks:
      dev_env:
        aliases:
          - plane.hgi.com
    environment:
      FILE_SIZE_LIMIT: ${FILE_SIZE_LIMIT:-5368709120}
      BUCKET_NAME: ${AWS_S3_BUCKET_NAME:-uploads}
    depends_on:
      - web
      - api
      - space
      - admin
    image: harbor.hwgeneralins.com/plane/proxy:1.2.1

volumes:
  redisdata:
  rabbitmq_data:
  pgdata:
networks:
  dev_env:
    external: true