# Generated by Django 4.2.17 on 2024-12-15 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0078_file_upload_settings'),
        ('db', '0086_issueversion_alter_teampage_unique_together_and_more'),
    ]

    operations = [
    ]
