# Generated by Django 4.2.17 on 2024-12-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0087_merge_20241215_1208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUploadSettings',
        ),
    ]
