# Generated by Django 4.2.18 on 2025-03-02 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0088_delete_fileuploadsettings'),
        ('db', '0091_issuecomment_edited_at_and_more'),
    ]

    operations = [
    ]
