# Generated by Django 4.2.18 on 2025-03-10 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0088_delete_fileuploadsettings'),
        ('db', '0092_alter_deprecateddashboardwidget_unique_together_and_more'),
    ]

    operations = [
    ]
