# Generated by Django 4.2.20 on 2025-05-01 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0093_page_moved_to_page_page_moved_to_project_and_more'),
        ('db', '0095_alter_issue_archived_at_alter_issue_completed_at_and_more'),
    ]

    operations = [
    ]
