# Generated by Django 4.2.20 on 2025-05-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0100_customfield_customfieldvalue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('text', '텍스트'), ('number', '숫자'), ('date', '날짜'), ('select', '선택'), ('multiselect', '다중선택'), ('url', 'URL'), ('email', '이메일'), ('project_member', '프로젝트 멤버'), ('project_members', '프로젝트 멤버(다중)')], max_length=20, verbose_name='필드 타입'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='key',
            field=models.CharField(max_length=50, verbose_name='고유 식별자'),
        ),
    ]
