# Generated by Django 4.2.20 on 2025-05-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0101_alter_customfield_field_type_alter_customfield_key'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customfield',
            name='custom_fiel_project_4e0084_idx',
        ),
        migrations.RemoveIndex(
            model_name='customfield',
            name='custom_fiel_key_81a9cd_idx',
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('select', '선택'), ('multiselect', '다중선택'), ('date', '날짜'), ('project_member', '프로젝트 멤버'), ('project_members', '프로젝트 멤버(다중)')], max_length=20, verbose_name='필드 타입'),
        ),
        migrations.AddIndex(
            model_name='customfield',
            index=models.Index(fields=['project', 'key'], name='custom_fiel_project_c6e5bf_idx'),
        ),
        migrations.AddIndex(
            model_name='customfield',
            index=models.Index(fields=['workspace', 'project', 'key'], name='custom_fiel_workspa_471742_idx'),
        ),
    ]
