# Generated by Django 4.2.17 on 2024-12-15 13:31

from django.db import migrations, models
import django.db.models.deletion
import plane.license.models.instance
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0005_rename_product_instance_edition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allowed_extensions', models.JSONField(default=plane.license.models.instance.get_default_extensions, help_text='허용되는 파일 확장자 목록')),
                ('max_file_size', models.PositiveIntegerField(default=5242880, help_text='최대 파일 크기 (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file_settings', to='license.instance')),
            ],
            options={
                'verbose_name': '파일 업로드 설정',
                'verbose_name_plural': '파일 업로드 설정',
                'db_table': 'file_upload_settings',
            },
        ),
    ]
