# Generated by Django 4.2.20 on 2025-03-18 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0093_merge_20250310_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultWorkspaceConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('role', models.PositiveSmallIntegerField(choices=[(20, 'Admin'), (15, 'Member'), (10, 'Viewer'), (8, 'Restricted'), (5, 'Guest')], default=15, help_text='자동 추가될 사용자에게 부여할 권한')),
                ('is_active', models.BooleanField(default=True, help_text='이 설정이 활성화되어 있는지 여부')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_workspace_configs', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Default Workspace Configuration',
                'verbose_name_plural': 'Default Workspace Configurations',
                'db_table': 'default_workspace_configs',
                'ordering': ('-created_at',),
            },
        ),
    ]
