# Generated by Django 4.2.20 on 2025-05-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0098_projectmattermostconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmattermostconfig',
            name='channel_id',
        ),
        migrations.RenameField(
            model_name='projectmattermostconfig',
            old_name='webhook_url',
            new_name='server_url',
        ),
        migrations.AlterField(
            model_name='projectmattermostconfig',
            name='server_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Mattermost 서버 URL'),
        ),
    ] 