# Generated by Django 4.2.22 on 2025-07-10 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0097_project_external_id_project_external_source'),
        ('db', '0105_page_is_folder'),
    ]

    operations = [
    ]
