# Generated by Django 4.2.22 on 2025-08-09 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0099_profile_background_color_profile_goals_and_more'),
        ('db', '0111_restnotificationconfig_and_more'),
    ]

    operations = [
    ]
