# Generated by Django 4.2.24 on 2025-09-30 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0104_cycleuserproperties_rich_filters_and_more'),
        ('db', '0112_merge_20250809_1814'),
    ]

    operations = [
    ]
