# Generated by Django 4.2.24 on 2025-10-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0114_alter_user_user_timezone'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customfieldvalue',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('custom_field', 'issue'), name='unique_active_custom_field_value'),
        ),
    ]
