# Generated by Django 4.2.25 on 2025-11-05 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0107_migrate_filters_to_rich_filters'),
        ('db', '0115_customfieldvalue_unique_active_custom_field_value'),
    ]

    operations = [
    ]
