# Generated by Django 4.2.25 on 2025-11-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0117_project_overview_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='overview_binary',
            field=models.BinaryField(blank=True, null=True, verbose_name='Project Overview Binary'),
        ),
        migrations.AlterField(
            model_name='project',
            name='overview',
            field=models.JSONField(blank=True, null=True, verbose_name='Project Overview'),
        ),
        migrations.AlterField(
            model_name='project',
            name='overview_html',
            field=models.TextField(blank=True, null=True, verbose_name='Project Overview HTML'),
        ),
    ]
