# Generated by Django 4.2.27 on 2025-12-18 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0112_auto_20251124_0603'),
        ('db', '0118_project_overview_binary_alter_project_overview_and_more'),
    ]

    operations = [
    ]
