# Generated by Django 4.2.20 on 2025-04-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0094_defaultworkspaceconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='archived_at',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='completed_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='is_draft',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Issue Name'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('none', 'None')], db_index=True, default='none', max_length=30, verbose_name='Issue Priority'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='sequence_id',
            field=models.IntegerField(db_index=True, default=1, verbose_name='Issue Sequence ID'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='sort_order',
            field=models.FloatField(db_index=True, default=65535),
        ),
        migrations.AlterField(
            model_name='issue',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='target_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='issuecomment',
            name='access',
            field=models.CharField(choices=[('INTERNAL', 'INTERNAL'), ('EXTERNAL', 'EXTERNAL')], db_index=True, default='INTERNAL', max_length=100),
        ),
        migrations.AlterField(
            model_name='issuecomment',
            name='edited_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='cycleissue',
            index=models.Index(fields=['issue_id', 'deleted_at'], name='cycle_issue_issue_i_4b2886_idx'),
        ),
        migrations.AddIndex(
            model_name='cycleissue',
            index=models.Index(fields=['cycle_id', 'deleted_at'], name='cycle_issue_cycle_i_dc98a0_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project', 'state'], name='idx_issue_proj_state'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project', 'created_at'], name='idx_issue_proj_created'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project', 'priority'], name='idx_issue_proj_priority'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project', 'is_draft'], name='idx_issue_proj_draft'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project', 'completed_at'], name='idx_issue_proj_completed'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project', 'archived_at'], name='idx_issue_proj_archived'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project', 'sequence_id'], name='idx_issue_proj_sequence'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project', 'sort_order'], name='idx_issue_proj_sort'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['parent', 'deleted_at'], name='idx_issue_parent_deleted'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project', 'state', 'sort_order'], name='idx_issue_proj_state_sort'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project', 'created_at'], name='idx_issue_proj_created_2'),
        ),
        migrations.AddIndex(
            model_name='issueassignee',
            index=models.Index(fields=['issue', 'deleted_at'], name='issue_assig_issue_i_c359d4_idx'),
        ),
        migrations.AddIndex(
            model_name='issueassignee',
            index=models.Index(fields=['assignee', 'deleted_at'], name='issue_assig_assigne_99e0ce_idx'),
        ),
        migrations.AddIndex(
            model_name='issuecomment',
            index=models.Index(fields=['issue', 'created_at'], name='issue_comme_issue_i_937053_idx'),
        ),
        migrations.AddIndex(
            model_name='issuecomment',
            index=models.Index(fields=['actor', 'created_at'], name='issue_comme_actor_i_0e8aa7_idx'),
        ),
        migrations.AddIndex(
            model_name='issuecomment',
            index=models.Index(fields=['access', 'created_at'], name='issue_comme_access_a2904f_idx'),
        ),
        migrations.AddIndex(
            model_name='issuecomment',
            index=models.Index(fields=['edited_at', 'created_at'], name='issue_comme_edited__b175c5_idx'),
        ),
        migrations.AddIndex(
            model_name='issuelabel',
            index=models.Index(fields=['issue', 'deleted_at'], name='issue_label_issue_i_fc286e_idx'),
        ),
        migrations.AddIndex(
            model_name='issuelabel',
            index=models.Index(fields=['label', 'deleted_at'], name='issue_label_label_i_1dad92_idx'),
        ),
        migrations.AddIndex(
            model_name='issuelink',
            index=models.Index(fields=['issue_id', 'deleted_at'], name='issue_links_issue_i_1b7e46_idx'),
        ),
    ]
