# Generated by Django 4.2.20 on 2025-05-27 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0097_defaultworkspaceconfig_excluded_user_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMattermostConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='활성화 여부')),
                ('webhook_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Webhook URL')),
                ('channel_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='채널 ID')),
                ('bot_token', models.CharField(blank=True, max_length=500, null=True, verbose_name='봇 토큰')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mattermost_configs', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mattermost_config', to='db.project', verbose_name='프로젝트')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_mattermost_configs', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '프로젝트 Mattermost 설정',
                'verbose_name_plural': '프로젝트 Mattermost 설정',
                'db_table': 'project_mattermost_configs',
            },
        ),
    ]
