# Generated by Django 4.2.20 on 2025-05-27 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0099_alter_projectmattermostconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='필드 이름')),
                ('key', models.CharField(max_length=50, verbose_name='API 키')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('field_type', models.CharField(choices=[('text', '텍스트'), ('number', '숫자'), ('date', '날짜'), ('select', '선택'), ('multiselect', '다중선택'), ('url', 'URL'), ('email', '이메일')], max_length=20, verbose_name='필드 타입')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='선택 옵션')),
                ('is_required', models.BooleanField(default=False, verbose_name='필수 여부')),
                ('default_value', models.JSONField(blank=True, null=True, verbose_name='기본값')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='추가 설정')),
                ('sort_order', models.FloatField(default=65535)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': '커스텀 필드',
                'verbose_name_plural': '커스텀 필드들',
                'db_table': 'custom_fields',
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('value', models.JSONField(verbose_name='필드 값')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='db.customfield', verbose_name='커스텀 필드')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='db.issue', verbose_name='이슈')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': '커스텀 필드 값',
                'verbose_name_plural': '커스텀 필드 값들',
                'db_table': 'custom_field_values',
                'ordering': ('custom_field__sort_order', 'created_at'),
                'indexes': [models.Index(fields=['issue', 'deleted_at'], name='custom_fiel_issue_i_f60041_idx'), models.Index(fields=['custom_field', 'deleted_at'], name='custom_fiel_custom__012239_idx')],
                'unique_together': {('custom_field', 'issue', 'deleted_at')},
            },
        ),
        migrations.AddIndex(
            model_name='customfield',
            index=models.Index(fields=['project', 'deleted_at'], name='custom_fiel_project_4e0084_idx'),
        ),
        migrations.AddIndex(
            model_name='customfield',
            index=models.Index(fields=['key'], name='custom_fiel_key_81a9cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customfield',
            unique_together={('project', 'key', 'deleted_at')},
        ),
    ]
