# Generated by Django 4.2.20 on 2025-06-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0102_remove_customfield_custom_fiel_project_4e0084_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('text', '텍스트'), ('select', '선택'), ('multiselect', '다중선택'), ('date', '날짜'), ('project_member', '프로젝트 멤버'), ('project_members', '프로젝트 멤버(다중)')], max_length=20, verbose_name='필드 타입'),
        ),
    ]
