# Generated by Django 4.2.21 on 2025-06-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0096_user_is_email_valid_user_masked_at'),
        ('db', '0103_alter_customfield_field_type'),
    ]

    operations = [
    ]
