# Generated by Django 4.2.22 on 2025-07-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0108_workflowapprovalrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowapprovalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
