# Generated by Django 4.2.22 on 2025-07-15 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0109_alter_workflowapprovalrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='issue_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='db.issuetype', verbose_name='이슈 타입'),
        ),
    ]
