# Generated by Django 4.2.22 on 2025-07-16 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0110_customfield_issue_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestNotificationConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='Default REST Notification', max_length=255)),
                ('endpoint_url', models.URLField(max_length=500)),
                ('method', models.CharField(default='POST', max_length=10)),
                ('headers', models.JSONField(default=dict)),
                ('json_template', models.JSONField(default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('timeout', models.IntegerField(default=30)),
                ('retry_count', models.IntegerField(default=3)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_notification_configs', to='db.workspace')),
            ],
            options={
                'verbose_name': 'REST Notification Config',
                'verbose_name_plural': 'REST Notification Configs',
                'db_table': 'rest_notification_configs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='customfieldvalue',
            name='custom_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_values', to='db.customfield', verbose_name='커스텀 필드'),
        ),
        migrations.CreateModel(
            name='RestNotificationLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('request_data', models.JSONField(null=True)),
                ('response_data', models.JSONField(null=True)),
                ('status_code', models.IntegerField(null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('attempt_count', models.IntegerField(default=1)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='db.restnotificationconfig')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('notification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rest_logs', to='db.notification')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'REST Notification Log',
                'verbose_name_plural': 'REST Notification Logs',
                'db_table': 'rest_notification_logs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('service_type', models.CharField(choices=[('slack', 'Slack'), ('discord', 'Discord'), ('teams', 'Microsoft Teams'), ('webhook', 'Generic Webhook'), ('custom', 'Custom API')], default='custom', max_length=50)),
                ('endpoint_url', models.URLField(blank=True, max_length=500, null=True)),
                ('method', models.CharField(default='POST', max_length=10)),
                ('headers', models.JSONField(default=dict)),
                ('json_template', models.JSONField(default=dict)),
                ('is_system_template', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'db_table': 'notification_templates',
                'ordering': ('service_type', 'name'),
            },
        ),
    ]
