# Generated by Django 4.2.25 on 2025-11-05 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0006_fileuploadsettings'),
        ('license', '0006_instance_is_current_version_deprecated'),
    ]

    operations = [
    ]
