FROM node:22-alpine

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY . .
RUN corepack enable pnpm && pnpm add -g turbo
RUN pnpm install
EXPOSE 3000

ENV TURBO_TELEMETRY_DISABLED=1

CMD ["pnpm","dev", "--filter=live"]
